spring:
  application:
    name: analyses-configurator-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          zkNodes: zookeeper
      bindings:
        output:
          destination: analyses
          content-type: application/json
server:
  port: 0
